-- AlterTable
ALTER TABLE "bancos" ADD COLUMN     "agencia" TEXT,
ADD COLUMN     "conta" TEXT,
ADD COLUMN     "dataSaldo" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "inativo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "saldoInicial" DOUBLE PRECISION NOT NULL DEFAULT 0;
